### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by jeremyf** [HeardLibrary/linked-data#17]
I'm exploring this software and looking to possibly utilize it.

However, before I begin, I'd like to know what is LICENSE for this project?

**Comment by baskaufs** [comment]
Hi @jeremyf . Sorry, I see that I haven't set a repo-wide license. I will fix that. Most of the significant scripts have a license statement: 

(c) 2020 Vanderbilt University. This program is released under a GNU General Public License v3.0 http://www.gnu.org/licenses/gpl-3.0

although I also stash a lot of trivial scripts here that I don't want to lose and they don't necessarily have a license statement. But the license above is what we use on all of the coding projects done by our office.
Steve

**Comment by baskaufs** [comment]
License is added
