### ISSUE TITLE
Use WikibaseIntegrator?

### ISSUE THREAD

**Issue by dpriskorn** [HeardLibrary/linked-data#23]
Hi it seems you have reinvented the wheel a bit in https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py

I can highly recommend you to rewrite it using https://www.wikidata.org/wiki/Wikidata:Wikidata:Tools/WikibaseIntegrator :)

**Comment by baskaufs** [comment]
@dpriskorn A major reason for developing VanderBot was not just to create a tool to write data to Wikibase instances, but rather to do it in a way that records tabular data that can be used to recreate the graph at the time of the upload. Another goal was to make the application usable by people without technical backgrounds. That's a significant barrier for entry for WikidataIntegrator-based applications. See the "Related work" section of https://doi.org/10.3233/SW-210443 for more on the rationale behind VanderBot.
