### ISSUE TITLE
OpenAlex is missing

### ISSUE THREAD

**Issue by dpriskorn** [HeardLibrary/linked-data#24]
https://github.com/HeardLibrary/linked-data/blob/bf68e0005194b9d458f0f9c86d9be7a8304abb56/publications/apis.md?plain=1#L1

see http://openalex.org/

**Comment by baskaufs** [comment]
Thanks for the link @dpriskorn . As you can see from the last modified date this wasn't a page that I've been actively maintaining. But I added the OpenAlex link.
